import { Component } from '@angular/core';
import { Router } from '@angular/router';
import { FormGroup } from '@angular/forms';

import { FormlyFieldConfig } from '@ngx-formly/core';

import { loginFormFields } from '@app/login/components/login-form/login-form.data';

import { Credentials } from '@app/login/models/login.interface';


/**
 * A component that is responsible for rendering the login form template and its functionalities
 */
@Component({
  selector    : 'app-login-form',
  templateUrl : './login-form.component.html',
  styleUrls   : ['./login-form.component.scss']
})
export class LoginFormComponent {
  
  /**
   * A variable that act as a parent login form
   *
   * @type {FormGroup}
   */
  form: FormGroup = new FormGroup({});
  
  /**
   * A variable that is an instance of the form parent's fields generated by ngx-formly
   *
   * @type {FormlyFieldConfig[]}
   */
  fields: FormlyFieldConfig[] = loginFormFields;
  
  /**
   * A variable that is an instance of the model's initial value
   *
   * @type {Credentials}
   */
  model: Credentials = { username: 'admin', password: 'admin' };
  
  constructor(private router: Router) { }
  
  /**
   * A function that is responsible for the form's submission. Since its a dummy login, the function's responsibility is
   * to redirect the user to speech page after submit button is clicked.
   *
   * @param {Credentials} credentials - the username and password value
   */
  submitForm(credentials: Credentials): void {
    this.router.navigate(['speech']);
  }

}
